# Generated by Django 5.1.6 on 2025-03-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
        migrations.AddField(
            model_name='product',
            name='Battery',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Аккумулятор'),
        ),
        migrations.AddField(
            model_name='product',
            name='Camera',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Камера'),
        ),
        migrations.AddField(
            model_name='product',
            name='Diagonal',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Диагональ'),
        ),
        migrations.AddField(
            model_name='product',
            name='Frame',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Корпус'),
        ),
        migrations.AddField(
            model_name='product',
            name='Front',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Фронтовая камера'),
        ),
        migrations.AddField(
            model_name='product',
            name='System',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Операционная система'),
        ),
        migrations.AddField(
            model_name='product',
            name='Technologies',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Технологии'),
        ),
        migrations.AddField(
            model_name='product',
            name='model',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Марка и модель'),
        ),
        migrations.AddField(
            model_name='product',
            name='release',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Дата выхода'),
        ),
        migrations.AlterField(
            model_name='product',
            name='depth',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Глубина'),
        ),
        migrations.AlterField(
            model_name='product',
            name='height',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Высота'),
        ),
        migrations.AlterField(
            model_name='product',
            name='width',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ширина'),
        ),
    ]
