# Generated by Django 5.1.6 on 2025-03-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0002_remove_product_description_remove_product_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Front',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Фронтальная камера'),
        ),
    ]
