# Generated by Django 5.1.6 on 2025-03-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0004_alter_product_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Battery',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Camera',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Diagonal',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Frame',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Front',
        ),
        migrations.RemoveField(
            model_name='product',
            name='System',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Technologies',
        ),
        migrations.RemoveField(
            model_name='product',
            name='depth',
        ),
        migrations.RemoveField(
            model_name='product',
            name='height',
        ),
        migrations.RemoveField(
            model_name='product',
            name='model',
        ),
        migrations.RemoveField(
            model_name='product',
            name='release',
        ),
        migrations.RemoveField(
            model_name='product',
            name='width',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание товара'),
        ),
    ]
