# Generated by Django 5.1.6 on 2025-03-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0005_remove_product_battery_remove_product_camera_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='depth',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Глубина'),
        ),
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Высота'),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ширина'),
        ),
    ]
