# Generated by Django 5.1.6 on 2025-03-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0007_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Guarantee',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Гарантия'),
        ),
    ]
