# Generated by Django 5.1.6 on 2025-03-05 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0008_product_guarantee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Guarantee',
        ),
        migrations.AddField(
            model_name='product',
            name='guarantee',
            field=models.IntegerField(blank=True, null=True, verbose_name='Гарантия'),
        ),
    ]
