# Generated by Django 5.1.6 on 2025-03-06 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0009_remove_product_guarantee_product_guarantee'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='memory',
            field=models.IntegerField(blank=True, null=True, verbose_name='Память'),
        ),
    ]
