# Generated by Django 5.1.6 on 2025-03-07 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0011_brand_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='slug',
        ),
    ]
