# Generated by Django 5.1.6 on 2025-03-07 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0012_remove_brand_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=models.SlugField(null=True, unique=True, verbose_name='Слаг товара'),
        ),
    ]
