# Generated by Django 5.1.6 on 2025-03-11 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0015_favoriteproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название области')),
            ],
            options={
                'verbose_name': 'Область (Регион)',
                'verbose_name_plural': 'Области (Регион)',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата начала заказа')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Статус заказа')),
                ('payment', models.BooleanField(default=False, verbose_name='Статус платежа')),
                ('shipping', models.BooleanField(default=True, verbose_name='Доставка')),
                ('customer', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='digital.profile', verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='В количестве')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digital.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digital.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название области')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='digital.region', verbose_name='Область (Регион)')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=150, verbose_name='Адрес доставки (улица, дом, кв): ')),
                ('phone', models.CharField(max_length=30, verbose_name='Номер телефона')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий к заказу')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата оформления доставки')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digital.city', verbose_name='Город доставки')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='digital.profile', verbose_name='Покупатель')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='digital.order', verbose_name='Заказ')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digital.region', verbose_name='Регион доставки')),
            ],
            options={
                'verbose_name': 'Доставку',
                'verbose_name_plural': 'Адреса доставок',
            },
        ),
    ]
