# Generated by Django 5.1.7 on 2025-03-15 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0017_alter_orderproduct_options_shippingaddress_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='digital.profile', verbose_name='Покупатель'),
        ),
    ]
